name: build-project-on-push
run-name: ${{ github.actor }} is pushing some branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd project/
      - run: npm ci
      - run: npm run build
      - run: serve -s build
