name: build-project-on-push
run-name: ${{ github.actor }} build project ubuntu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ./project/ && npm i
      - run: cd ./project/ && npm run build
