name: test-project-on-push
run-name: ${{ github.actor }} test project 
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cd ./project/ && npm i
      - run: cd ./project/ && npm run test
